# Example configuration for Lambda Chat
# Copy this file to `config.yml` and then set the values appropriately

# The Google OAuth Client ID
# Visit: https://console.developers.google.com/project
# To create a project, enable the Google+ API, and create an ID
# Set the Javascript Origin to the S3 bucket URL
google_oauth_client_id: TODO

# The AWS region to do everything in
region: us-east-1

# The name of the S3 bucket to use for the website
# This must be unique across all AWS accounts
s3_bucket: lambda-chat

# The S3 object key for the chat data
data_key: data.json

# The ARN of the IAM role the website will assume to be able to send messages
# using SNS
website_iam_role_arn: arn:aws:iam::TODO

# The ARN of the SNS topic to publish chat messages to, and for Lambda to read
sns_topic_arn: arn:aws:sns::TODO
