---
# change profile and region to meet your needs
profile: cloudnative-dev
region: us-west-2
resources: resources.json
iam:
  policy:
      description: A policy used with the Kappa SNS->DynamoDB example
      name: LambdaChatDynamoDBPolicy
      document: LambdaChatDynamoDBPolicy.json
  role:
      name: LambdaChatDynamoDBRole
lambda:
  name: LambdaChatDynamoDB
  zipfile_name: LambdaChatDynamoDB.zip
  description: A simple chat app with S3/SNS/DynamoDB/Lambda
  path: code/
  handler: LambdaChatDynamoDB.handler
  runtime: nodejs
  memory_size: 128
  timeout: 3
  event_sources:
    -
      # Change this to point to your DynamoDB stream.
      # Note that you must be in the DynamoDB Streams preview.
      arn: arn:aws:dynamodb:us-west-2:860421987956:table/lambdachat/stream/2015-09-09T17:52:45.927
      batch_size: 1
      starting_position: LATEST
      enabled: true
  test_data: input.json
  